#!/bin/bash

set -e # exit on any errors

if [ -z ${AWS_KEY+x} ]; then
  echo "The AWS_KEY variable must be set to ssh";
  exit 1;
fi

if [ ! -f ${AWS_KEY} ]; then
    echo "The file specified by AWS_KEY does not exist"
    exit 1;
fi

# The file redirect on the last (ssh) line does not resolve the path correctly, so we use a little magic here to get the directory
# that contains the script files
SCRIPTS_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

source ${SCRIPTS_DIR}/configuration.txt

EC2_IP=`get_ec2_public_ip`

ssh -i ${AWS_KEY} ec2-user@${EC2_IP}
