#!/bin/bash

set -e # exit on any errors
trap "echo; exit" INT

if [ -z ${AWS_KEY+x} ]; then
  echo "The AWS_KEY variable must be set to ssh";
  exit 1;
fi

if [ ! -f ${AWS_KEY} ]; then
    echo "The file specified by AWS_KEY does not exist"
    exit 1;
fi

source configuration.txt

EC2_IP=`get_ec2_public_ip`

ssh -i ${AWS_KEY} ec2-user@${EC2_IP}
